name: linea-build
run-name: ${{ github.actor }} is building.
on: 
  push:
    branches:
      - linea
jobs:
  ContractTesting:
    runs-on: ubuntu-latest
    container: alexchenqr/solidity-smart-contract:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: npx hardhat --version
      - name: Run tests
        env:
          PRIVATE_KEY: ${{ secrets.TEST_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          FORK_TEST_ADDR: ${{ secrets.FORK_TEST_ADDR }}
        run: npx hardhat clean && npx hardhat compile && npx hardhat test
