name: Testing
run-name: ${{ github.actor }} is testing.
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container: alexchenqr/solidity-smart-contract:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "This job's status is ${{ job.status }}."
      - run: npx hardhat --version
      - run: touch .env && cat ${{ secrets.TEST_KEY }} > .env
      - run: npx hardhat clean
