name: Testing
run-name: ${{ github.actor }} is testing.
on: [push]
jobs:
  ContractTesting:
    runs-on: ubuntu-latest
    container: alexchenqr/solidity-smart-contract:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "This job's status is ${{ job.status }}."
      - run: npm install
      - run: npx hardhat --version
      - name: Run tests
        env:
          PRIVATE_KEY: ${{ secrets.TEST_KEY }}
        run: npx hardhat clean && npx hardhat compile && npx hardhat test
